image: themattrix/tox

stages:
  - static_check
  - tests

before_script:
  - pyenv global $(pyenv global | grep "^3.6")

static_check:
  stage: static_check
  script:
    - flake8 .

tests:
  stage: tests
  script:
  - tox
